### ISSUE TITLE
Better instructions for building & testing

### ISSUE THREAD

**Issue by dradetsky** [touchifyapp/spec2ts#12]
I would like to contribute to this repo. For example, I note that [here](https://github.com/touchifyapp/spec2ts/blob/master/packages/jsonschema/README.md) it indicates that support for `patternProperties` has not yet been added, and I wanted to take a stab at adding it. Unfortunately, I'm not terribly comfortable with lerna & have been using extremly hacky methods to try out changes to this code so far.

If you made a very simple `contributing.md` with just something like 

> this is what I do:
> lerna something-or-other
> npm run some-thing
> npm run test-this-somehow

and so on, showing how you build this project, try out changes in a 2nd repo, run tests (are there tests?), etc, that would significantly lower the barrier to entry for contributing a PR.

**Comment by mtrimolet** [comment]
@dradetsky I'm working on it, see #14.
