### ISSUE TITLE
[@spec2ts/openapi] [feature request] Support for JSON schema const keyword

### ISSUE THREAD

**Issue by marcogrcr** [touchifyapp/spec2ts#3]
I would love to have support for the JSON schema `const` keyword [introduced in JSON schema Draft 7](https://tools.ietf.org/html/draft-wright-json-schema-validation-01#section-6.24):

```yml
# spec.yml
openapi: 3.0.3
info:
  title: example
  version: 1.0.0
paths:
  /example:
    get:
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                const: my value
```

```bash
npx oapi2ts ./spec.yml
```

**Expected output:**

```ts
export type GetExampleResponse = "my value";
```

**Actual output:**

```ts
export type GetExampleResponse = any;
```

**Workaround:**

Use `enum: ["my value"]`, but it would be great to add support for this `const` keyword.

**Environment:**
- `@spec2ts/openapi v1.2.1`

---

**P.S.** Thanks for the great library!

**Comment by mtrimolet** [comment]
Hello @marcogrcr !
Good point, this will definitely be added to the upcoming release.
You can see PR #9 for implementation details.
